/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package d.Vistas;

import c.AccesoDatos.alumnoData;
import c.AccesoDatos.inscripcionData;
import c.AccesoDatos.materiaData;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author stamp
 */
public class inicio extends javax.swing.JFrame {

    JInternalFrame frameInicio = null;
    AlumnoPorMateria alumnXMateria;
    FormularioDeAlumno formAlumn;
    FormularioDeMateria formMateria;
    ManejoDeInscripciones manDeIns;
    ManipulacionDeNotas manDeNotas;

    alumnoData AlumnoData;
    inscripcionData InsData;
    materiaData MatData;

    public inicio() {
        initComponents();
        this.AlumnoData = new alumnoData();
        this.InsData = new inscripcionData(MatData,AlumnoData);
        this.MatData = new materiaData();
        //AlumnoData
        formAlumn = new FormularioDeAlumno(AlumnoData);
        Escritorio.add(formAlumn);
        //MateriaData
        formMateria = new FormularioDeMateria(MatData);
        Escritorio.add(formMateria);
        //Inscripcion
        manDeIns = new ManejoDeInscripciones(InsData, MatData, AlumnoData);
        Escritorio.add(manDeIns);
        //Manipulacion De Notas
        manDeNotas = new ManipulacionDeNotas(AlumnoData, InsData);
        Escritorio.add(manDeNotas);
        //AlumnoPorMateria
        alumnXMateria = new AlumnoPorMateria(MatData, InsData);
        Escritorio.add(alumnXMateria);               
    }
    
    
    private void frameInicio(JInternalFrame jI){
        if(frameInicio != null){
            frameInicio.hide();
        }
        frameInicio = jI;
        frameInicio.setVisible(true);
        frameInicio.setLocation(0,0);
        frameInicio.moveToFront();
        
        try{            
            frameInicio.setSelected(true);            
        }catch(PropertyVetoException ex){
            JOptionPane.showMessageDialog(null, "No se puede abrir" );
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jFormAlum = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jFormMat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jManejoInsc = new javax.swing.JMenuItem();
        jManejoNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jAlumXMateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(102, 102, 102));
        Escritorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 153), null, null));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu1.setBackground(new java.awt.Color(102, 102, 102));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Alumno");

        jFormAlum.setText("Formulario de Alumno");
        jFormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormAlumActionPerformed(evt);
            }
        });
        jMenu1.add(jFormAlum);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(102, 102, 102));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Materia");

        jFormMat.setText("Formulario de Materia");
        jFormMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormMatActionPerformed(evt);
            }
        });
        jMenu2.add(jFormMat);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(102, 102, 102));
        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Administracion");

        jManejoInsc.setText("Manejo de Inscripciones");
        jManejoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManejoInscActionPerformed(evt);
            }
        });
        jMenu3.add(jManejoInsc);

        jManejoNotas.setText("Manipulacion de Notas");
        jManejoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManejoNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jManejoNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(102, 102, 102));
        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setText("Consultas");

        jAlumXMateria.setText("Alumnos por Materia");
        jAlumXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlumXMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jAlumXMateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(102, 102, 102));
        jMenu5.setForeground(new java.awt.Color(0, 0, 0));
        jMenu5.setText("Salir");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormAlumActionPerformed
       
        frameInicio(formAlumn);
    }//GEN-LAST:event_jFormAlumActionPerformed

    
    private void jFormMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormMatActionPerformed
        
        frameInicio(formMateria);     
    }//GEN-LAST:event_jFormMatActionPerformed

    
    private void jManejoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManejoInscActionPerformed

        frameInicio(manDeIns);
    }//GEN-LAST:event_jManejoInscActionPerformed

    
    private void jManejoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManejoNotasActionPerformed
        
        frameInicio(manDeNotas);
    }//GEN-LAST:event_jManejoNotasActionPerformed

    
    private void jAlumXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlumXMateriaActionPerformed
        
        frameInicio(alumnXMateria);
    }//GEN-LAST:event_jAlumXMateriaActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem jAlumXMateria;
    private javax.swing.JMenuItem jFormAlum;
    private javax.swing.JMenuItem jFormMat;
    private javax.swing.JMenuItem jManejoInsc;
    private javax.swing.JMenuItem jManejoNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
